### ISSUE TITLE
Printed ballots with long infotext

### ISSUE THREAD

**Issue by aosterkorn** [Tabbie2/issues#1]
Printed ballots wrap badly for rounds with (very) long information text.
Might be better to start a new page for every ballot and/or omit the info text or scale the font size.

![infotext](https://cloud.githubusercontent.com/assets/15693254/11003737/a5bfdee6-84b4-11e5-955a-d3deaf41d7b1.png)

**Comment by chief-nerd** [comment]
Would you consider double side printing be an option?

**Comment by janmax** [comment]
Yes. If double double site printing is not available one could just leave out every second page and/or printing the fact sheets afterward in a separate printing job.
