### ISSUE TITLE
Useful naming of exported lists (Tab, Adjudicators, teams...) instead of grid-export.*

### ISSUE THREAD

**Issue by janmax** [Tabbie2/issues#11]
At the moment all exports are named grid-export.\* which is a bit messy. Maybe not the most important enhancement but still the downloads folder gets more structured.

**Comment by rscoates** [comment]
This is on ExportMenu.php line 845, but it's a text string, not a variable - maybe just take the date?

**Comment by rscoates** [comment]
This is harder than I thought.

**Comment by janmax** [comment]
I thought of something like {Adjudicator|Tab|Team}_export_{date}.*
