### ISSUE TITLE
Internal Server Error 500 after deleting Teams.

### ISSUE THREAD

**Issue by janmax** [Tabbie2/issues#12]
No negativ consequences, but still a bug. I believe this should be reproducible/happened every time while Zeit Debatte Göttingen.

**Comment by chief-nerd** [comment]
Does it happen after R1 - or before R1?

**Comment by janmax** [comment]
Before. We imported a csv and had to delete some teams manually before reinserting them.

**Comment by janmax** [comment]
The deleting worked, we just ended on a page saying Error 500.
