### ISSUE TITLE
Add Trainees

### ISSUE THREAD

**Issue by rscoates** [Tabbie2/issues#18]
Add trainee as a tag for judges (wings with no voting privileges that appear as high wings)

**Comment by chief-nerd** [comment]
Like that one - I would do it via a database flag that says: trainee ? 1:0
needs a migration ;)

**Comment by chief-nerd** [comment]
There is a new function = 2 for adjudicator in panel that symbolises a trainee ... still you need a flag in adjudicator since you would have to check every trainee every round again as trainee.
(Looking in the previous round would I guess be too memory consuming)
