### ISSUE TITLE
Two Accounts issue

### ISSUE THREAD

**Issue by GaryMoloney** [Tabbie2/issues#19]
I seem to have accidentally created two accounts under my own name (Gary Moloney) using the email address; garymoloney93@gmail.com. What is the best way to resolve this issue?

**Comment by chief-nerd** [comment]
Hey @GaryMoloney - yea I see you have 2 different email addresses .... Since the system is matching the users according to their emails this can happen. Only way to resolve this is that i have to manually change the data ....
Any ideas on how to prevent this?
