### ISSUE TITLE
Import of participant data with incorrect email address

### ISSUE THREAD

**Issue by aosterkorn** [Tabbie2/issues#2]
The import of participant data (speakers, judges) from a CSV file produces an uncatched exception if one of the email addresses is not valid (by typo or by johndoe@example.com vs john.doe@example.com issues)
It would be better to import all valid data sets and give the user a message concerning the flawed address.

**Comment by chief-nerd** [comment]
Thx for reporting! Yea I know of the import function to be critical part. 
I'll have a look at it during the weekend.

**Comment by chief-nerd** [comment]
Fixed with JakobReiter/tabbie2/a6f980a
