### ISSUE TITLE
Adjudicator Reassignment

### ISSUE THREAD

**Issue by tierneyvt** [Tabbie2/issues#20]
Essentially what happen was:
- drew round, went to print ballots. 
- Needed to change motion, also realised some people were clashed out.
- because I had attempted to print the ballots the drag and drop for the adjudicators was no longer working.
- the drop down menu wouldn't work, either to move a chair to a wing or a wing to a chair. 

Any ideas?

**Comment by chief-nerd** [comment]
Try refresh the page ... seems like the javascript crashed somehow.

**Comment by tierneyvt** [comment]
Perfect Jakob,if that happens again today I will do that.

I owe you two pints at worlds so far. :)

V

On 27 November 2015 at 08:10, Jakob notifications@github.com wrote:

> Try refresh the page ... seems like the javascript crashed somehow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tabbie2/issues/issues/20#issuecomment-160065048.

## 

_Valerie T. Tierney_

Bachelor of Veterinary Medicine (MVB) 2017

Phone: 0879202535
Email: valerie.tierney@ucdconnect.ie
