### ISSUE TITLE
URL slug generation with non ASCII characters

### ISSUE THREAD

**Issue by chief-nerd** [Tabbie2/issues#23]
When naming a tournament with non ASCII characters - meaning UTF8 like russian, etc - the chars get stripped and the url looks like tabbie.org/-2015/

Idea: Make URL field for manual input. Or validation and re-enter if string is ""

**Comment by chief-nerd** [comment]
also we wanna prohibit  Tournament-IV-2016-2016

**Comment by rscoates** [comment]
Fancy fix with RegEx, or less fancy with cleaning strings.
