### ISSUE TITLE
Class 'URLify' not found

### ISSUE THREAD

**Issue by geoangelotti** [Tabbie2/issues#32]
When creating a new Tournament a fatal PHP Fatal Error gets generated when creating a new SlugURL:
line 245  in /var/www/virtual/tabbie/tabbie2/tabbie2.git/common/models/Tournament.php
$potential_slug = URLify::filter($this->fullname); //An error occurs hear Class 'URLify' not found

**Comment by chief-nerd** [comment]
Should be fixed now ... We added a new module for non ascii URL.
