### ISSUE TITLE
Preset Panel duplication

### ISSUE THREAD

**Issue by CalWor** [Tabbie2/issues#33]
Preset panels occasionally (regularly in round 5) drop the same panel into multiple rooms multiple times, so there are several judges in the draw several times and it's all a mess. When it does this, it deletes one panel from the list of presets, is this part of the issue?

**Comment by Lord-Bean** [comment]
I had this happening to me when drawing the first round at the Erasmus Rotterdam Open this weekend, it dropped every panel in every room (as far as I took the time to look at at least).

**Comment by rscoates** [comment]
https://github.com/JakobReiter/Tabbie2/commit/3704a2cfc374de6ee119a8806d56bbcc03d9b1fd
