### ISSUE TITLE
Possible features German CAs like

### ISSUE THREAD

**Issue by aosterkorn** [Tabbie2/issues#4]
Uncommented feedback from the CAs during ZEIT DEBATTE Göttingen:
- activate judges after creation of a round: We created the round for Saturday morning on Friday evening when some of the adjudicators had not arrived. As it was not entirely clear that they would be there for the next round we deactivated them. On Saturday morning we were not able to integrate them into the draw. Nice feature would be a list of deactivated judges over the draw adjustment menu where judges can be dropped or dragged from.
- German CAs like to have a printed version of the draw preferably without the points/strength of a room to show it to participants and judges.
- the CAs would prefer to enter the text of the motion at the end of the draw creation process (just to have a look on the draw for the next round), compromise might be to give an option of changing the text of the motion after the creation of the round.

**Comment by chief-nerd** [comment]
split up in issues
