### ISSUE TITLE
Strike participant with institution

### ISSUE THREAD

**Issue by aosterkorn** [Tabbie2/issues#6]
It seems to me the only way to strike a team with an institution is to strike the team with all adjudicators from that institution.
The most common situation of strikes is that a team member affiliated with an institution in the past.
Hence it might be easier to let participants clash with institutions (or assign more than one institution to users) instead of teams with adjudicators directly.

**Comment by chief-nerd** [comment]
All status quo
Adjudicators are strikes from all institutions they affiliate with + a 6 month period (roughly 1 Semester)
When importing the user gets his/her 1 institution, but more can be added by the user.
